name: Deploy

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        permissions:
            id-token: write
            contents: read

        steps:
            - name: Log in to Azure
              uses: azure/login@v1
              with:
                enable-AzPSSession: true
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                # client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

            - name: Deploy ARM Template
              uses: azure/arm-deploy@v1
              with:
                scope: resourcegroup
                subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                resourceGroupName: ${{ secrets.AZURE_RG}}
                template: ./src/InfrastructureAsCdoe/main.bicep
                # parameters: ./path/to/your/parameters.json